### ISSUE TITLE
no value

### ISSUE THREAD

**Issue by ghost** [wangzhe0623/Object-Detection-Evaluation-Tool#4]
Hi @wangzhe0623   my class is 1 which means  value will be 2 including backgroud i tried test.pybut get nothing as shown below.
![ask](https://user-images.githubusercontent.com/58855073/89123734-3f26c880-d4ef-11ea-9f2b-9c99a765da07.png)

**Comment by wangzhe0623** [comment]
@lrscse Hi, It seems txt file is not loaded, can you offer more information about your input files?

**Comment by ghost** [comment]
Hi @wangzhe0623  i have only 1 class i.e tumor detected in MRI images.. i want to produce AUC  and PR using your method..
i have insert prediction and  ground truth annotation as shown in below figure.. can you please tell where is wrong. 19,47,49 etc are images file name. 
![55](https://user-images.githubusercontent.com/58855073/89300338-afffe900-d685-11ea-9afb-fbc11d397341.png)

**Comment by wangzhe0623** [comment]
@lrscse Make sure "class_map_temp" in evaluation.py  and "class_map" in io_file.py were modified as you need; and please show me samples of your "prediction" and "test_annos".

**Comment by ghost** [comment]
Hi @wangzhe0623  i made necessary changes still doesnot work.. "orediction" and "test_annos" are shown in above screenshot.
on "prediction" i add confidence score like you did in your repository. i.e.
1  131 175 234 234 0.84
 and on "test_annos" as:
1 153 166 213 244

**Comment by wangzhe0623** [comment]
@lrscse That seems no problem, and how did you run this code? In terminal?

**Comment by ghost** [comment]
@wangzhe0623  yes in terminal.. what could else be the problem?

**Comment by wangzhe0623** [comment]
@lrscse :-(  I can't locate bugs with this information, maybe you can add breakpoint or use pdb to find out what's wrong in the end. Sorry~
